### ISSUE TITLE
Position changes after saving ModelForm without position field

### ISSUE THREAD

**Issue by jnm** [jpwatts/django-positions#28]
Hello,

After upgrading to 0.5.1, I noticed that when an object is saved via a `ModelForm` that does not include a position field, that object's position moves to last place. I think this is the responsible change: https://github.com/jpwatts/django-positions/commit/cfdb4847757a9d59caf026c0df95a451f292d67b#diff-d225dfacb4effdf5497b014c35da0d4eR92

I created a minimal project to demonstrate the issue using the models in the "photo" example. It's housed at https://github.com/jnm/django-positions-test, and the ModelForm I use there is:

    class SillyForm(django.forms.ModelForm):
        class Meta:
            model = Photo 
            fields = ['name',]

**Comment by barseghyanartur** [comment]
Same here. The last object saved gets the last position and all numbers being rebuilt. I didn't have time to look at it. Did anyone of those using `django-position` managed to solve the issue?

**Comment by barseghyanartur** [comment]
Update, solve in my fork. See the related [pull request](https://github.com/jpwatts/django-positions/pull/43).
