### ISSUE TITLE
Django 2.0 "'PositionField' object has no attribute 'get_cache_name'"

### ISSUE THREAD

**Issue by jasonHav** [jpwatts/django-positions#57]
Hi Guys,

I'm updating an (admittedly inherited) project to Django 2.0 and it uses your Django-positions library.

Since the upgrade, I'm getting the following error when rendering a PositionField:

> 'PositionField' object has no attribute 'get_cache_name'

I checked Django's side and it looks like that's no longer on IntegerFields (though I may be wrong). Any ideas or tips on where to go from where?

**Comment by scanf** [comment]
Was going to try out this module but hitting the same issue. Is there any fix for it?
Thanks.

**Comment by forrestp** [comment]
ok, I got everything working and cut a 0.6.0 release. definitely let me know if there are any problems.

**Comment by JulianTenschert** [comment]
I've got the same error with multi-table model inheritance, `parent_link` is set as described in the README.

error:
> AttributeError at /admin/courses/imageslide/
> 'ImageSlide' object has no attribute '_position_cache_'

models.py:
```python
class Slide(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='slides')
    position = PositionField(collection='course', parent_link='slide_ptr_id')


class ImageSlide(Slide):
    image = models.ImageField(upload_to=upload_file_path, max_length=255)


class QuizSlide(Slide):
    question = models.CharField(max_length=255)
```

Has anyone tried django-positions with Django 2.0 and multi-table model inheritance yet?
