### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by clovis1122** [jpwatts/django-positions#64]
Hello!

On djangopackages this library is marked as not supporting Python3: https://djangopackages.org/packages/p/django-positions/

Wanted to check if there're plans to support Python3 in the future.

**Comment by jpwatts** [comment]
I'm no longer actively maintaining this package. @forrestp has done more recent maintenance and might be able to answer your question.

**Comment by clovis1122** [comment]
@jpwatts, thanks for the reply. I'll wait for @forrestp to see if we can get this sorted.

**Comment by forrestp** [comment]
python3 and django2 support was added in [v0.6.0](https://pypi.org/project/django-positions/) - not sure how to update this on djangopackages.

see [travis](https://travis-ci.org/jpwatts/django-positions) for specific versions.

I'll add that I don't actively use this project anymore, and would recommend you consider [django-ordered-model](https://github.com/bfirsh/django-ordered-model) as an alternative if you aren't using django-positions already.
